# Generated by Django 4.2.7 on 2023-11-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=500)),
                ('id_sence', models.IntegerField()),
                ('comuna', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('modalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=10)),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('img_ci_frontal', models.FileField(upload_to='')),
                ('img_ci_posterior', models.FileField(upload_to='')),
                ('rsh', models.FileField(upload_to='')),
                ('direccion', models.CharField(max_length=500)),
                ('comuna', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.cursos')),
            ],
        ),
    ]
