# Generated by Django 4.2.7 on 2023-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_cursos_inscritos_remove_inscritos_img_ci_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='img_field_frontal',
            field=models.FileField(error_messages='Sobrescribiendo', upload_to='archivos_participantes/', verbose_name='Imagen frontal del CI'),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='img_field_posterior',
            field=models.FileField(error_messages='Sobrescribiendo', upload_to='archivos_participantes/', verbose_name='Imagen posterior del CI'),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='rsh',
            field=models.FileField(error_messages='Sobrescribiendo', upload_to='archivos_participantes/', verbose_name='Registro social de hogares'),
        ),
    ]
