# Generated by Django 4.2.7 on 2023-12-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_alter_inscritos_img_field_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.cursos_inscritos'),
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
