# Generated by Django 4.2.7 on 2023-12-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_alter_inscritos_curso_delete_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscritos',
            name='genero',
        ),
        migrations.AddField(
            model_name='inscritos',
            name='escolaridad',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inscritos',
            name='pais_origen',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='inscritos',
            name='sexo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='comuna',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.cursos_inscritos'),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='direccion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='img_field_frontal',
            field=models.FileField(error_messages='Sobrescribiendo', null=True, upload_to='archivos_participantes/', verbose_name='Imagen frontal del CI'),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='img_field_posterior',
            field=models.FileField(error_messages='Sobrescribiendo', null=True, upload_to='archivos_participantes/', verbose_name='Imagen posterior del CI'),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='nombre_completo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='rsh',
            field=models.FileField(error_messages='Sobrescribiendo', null=True, upload_to='archivos_participantes/', verbose_name='Registro social de hogares'),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
